import os

DB_HOST = os.environ['CK_DB_HOST']
DB_USER = os.environ['CK_DB_USER']
DB_PASS = os.environ['CK_DB_PASS']
DB_NAME = os.environ['CK_DB_NAME']

CLOUDINARY_CLOUD_NAME = os.environ['CK_CLOUDINARY_CLOUD_NAME']
CLOUDINARY_API_KEY = os.environ['CK_CLOUDINARY_API_KEY']
CLOUDINARY_API_SECRET = os.environ['CK_CLOUDINARY_API_SECRET']

ADMIN_PASS = os.environ['CK_ADMIN_PASS']
