PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS 
POST (
    POST_CODE TEXT PRIMARY KEY NOT NULL, 
    POST_CONTENT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS
TAG (
    TAG_CODE TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS
POSTTAG (
    TAG_CODE TEXT,
    POST_CODE TEXT,
    FOREIGN KEY(TAG_CODE) REFERENCES TAG(TAG_CODE) ON DELETE CASCADE,
    FOREIGN KEY(POST_CODE) REFERENCES POST(POST_CODE) ON DELETE CASCADE,
    UNIQUE(TAG_CODE, POST_CODE)
);
